### ISSUE TITLE
THUMBNAIL_LIMIT check needs a fallback value / breaks g-e-t outside GNOME

### ISSUE THREAD

**Issue by jlu5** [GLolol/gnome-exe-thumbnailer#1]
When testing gnome-exe-thumbnailer on Debian testing with Cinnamon DE, the THUMBNAIL_LIMIT line at https://github.com/gnome-exe-thumbnailer/gnome-exe-thumbnailer/blob/upstream/usr/bin/gnome-exe-thumbnailer#L188 breaks as `org.gnome.nautilus.preferences` doesn't exist.

Could a fallback value be added so that gnome-exe-thumbnailer still works on non-GNOME desktops? (0.9.3 worked fine). Otherwise, a dependency on Nautilus (nautilus-data) should probably be added.

CC @YokoZar @jan-nekvasil

**Comment by MangaD** [comment]
Excuse my ignorance, but why is it necessary to have a file size limit? And isn't 10MiB too low? Currently many of my EXE files are not showing the icon on thunar because of this...

**Comment by jlu5** [comment]
The file size limit is due to an old bug in the tool exe-thumbnailer uses to extract icons: https://bugs.launchpad.net/ubuntu/+source/icoutils/+bug/614918

**Comment by MangaD** [comment]
I see. Fixing the bug introduced a new one though. ^^'
