### ISSUE TITLE
Support for Deepin DE

### ISSUE THREAD

**Issue by xmine64** [GLolol/gnome-exe-thumbnailer#13]
sorry for asking here, I can't find anything about how to configure my system to display icons.
I'm using deepin desktop on arch linux.
this is a screenshot after installing this by `yay -S exe-thumbnailer`
![deepinscreenshot_select-area_20190219160350](https://user-images.githubusercontent.com/21140798/53015304-02345680-3460-11e9-88ad-3cb89d025175.png)

**Comment by vinyanalista** [comment]
I've made a [RPM package](https://software.opensuse.org/package/exe-thumbnailer) for exe-thumbnailer. I took as reference the [DEB package](https://packages.ubuntu.com/disco/exe-thumbnailer) that already exists for Ubuntu. Although I successfully built it and installed it, it does not seem to work... is there anything else that needs to be done (other than copying files to `/usr`?)

I'm using GNOME 3.26.2 on openSUSE Leap 15.1.

**Comment by jlu5** [comment]
After looking at this further, it seems GNOME 3.26 and later runs external thumbnailers in a sandbox, but the default configuration doesn't work for all distros.

Some relevant bug links:
http://www.bernaerts-nicolas.fr/linux/74-ubuntu/360-ubuntu-nautilus-external-thumbnailer-failure
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902288
https://gitlab.gnome.org/GNOME/gnome-desktop/issues/4 (it seems like some related fixes made it into GNOME 3.32?)

**Comment by xmine64** [comment]
new comments on this issue aren't related to my question.
I was asking how can I config deepin file manager to show thumbnails, it isn't related to GNOME at all.
Please open a new issue.

**Comment by vinyanalista** [comment]
But that's the point: if I understood it right, you should just install it and it should just work.

It is not working for you not because you need to do anything else (you asked "how to configure my system"), but because it is not working at all (even for people using desktops other than Deepin and distributions other than Arch Linux).

I'm going to read those links and see if I can help somehow...

**Comment by xmine64** [comment]
dde file manager is different from nautilus. I can point out that nautilus is based on GTK and dde file manager is based on Qt5/DTK.
for now, I don't have deepin; I use thunar on i3, I don't need any answer or deepin support for your program anymore, but problems with the thumbnailer on nautilus is not related to my question at all.

**Comment by xmine64** [comment]
Note that at the time I was using your program, it was working on nautilus.
(Sorry I can't edit, I use opera mini that has a basic javascript support, edit button doesn't work)

**Comment by vinyanalista** [comment]
exe-thumbnailer works if I call it manually:

```
$ exe-thumbnailer winbox.exe winbox.png
```

![image](https://user-images.githubusercontent.com/1576506/63468556-95b20880-c43e-11e9-87ac-afa8654dc8d2.png)

(that is Nautilus 3.26.2)

It also works using the Thunar 1.8.4 file manager:

![image](https://user-images.githubusercontent.com/1576506/63468727-f04b6480-c43e-11e9-96b3-6a7fab191168.png)

So, @jlu5, it seems the problem regarding Nautilus is really reduced to running in sandbox. Do you have any idea on how to debug that? I found a guy that opened [an issue on Nautilus](https://gitlab.gnome.org/GNOME/nautilus/issues/543) and GNOME developers told him to ask on IRC.

@mmdmine, using openSUSE, I just installed thunar and exe-thumbnailer and it simply worked. No manual configuration needed. I don't know if you need to do anything else on the distribution or desktop environment you are using.

**Comment by jlu5** [comment]
@mmdmine Sorry for the confusion! AFAIK earlier versions of Deepin used Nautilus as its file manager, but it appears this is not the case anymore. I'll clone the GNOME parts as a different issue.

In general, exe-thumbnailer doesn't require any set up to work on FMs that support thumbnailers specified in /usr/share/thumbnailers: https://wiki.gnome.org/DraftSpecs/ThumbnailerSpec. This is the case for Thunar (when [tumbler](https://github.com/xfce-mirror/tumbler/blob/master/README) is installed), Caja, Nautilus, etc.

I'm not familiar with DDE so I don't know if it actually supports this spec. If it does not, it needs to be added as a feature there first.

**Comment by yaaaaa** [comment]
most wanted to me, deepin support will be a great.

**Comment by eduardomozart** [comment]
I believe that I figure out the function that Deepin uses to generate the thumbnail file. Instead of following FreeDesktop filename standard, they apparently follow their own: https://github.com/linuxdeepin/deepin-riscv/blob/07b566d791e09187bed3664b4a9848c117ead653/dde-api-5.5.5/thumbnails/loader/loader.go#L111

**Comment by jlu5** [comment]
> I believe that I figure out the function that Deepin uses to generate the thumbnail file. Instead of following FreeDesktop filename standard, they apparently follow their own: https://github.com/linuxdeepin/deepin-riscv/blob/07b566d791e09187bed3664b4a9848c117ead653/dde-api-5.5.5/thumbnails/loader/loader.go#L111

Thanks for taking a look!

Unfortunately supporting desktops outside the Freedesktop.org specification is out of scope for exe-thumbnailer (and its successor icoextract). It's simply too difficult to integrate things otherwise.
