### ISSUE TITLE
Add category to .desktop

### ISSUE THREAD

**Issue by RegretfulCarrot** [GLolol/gnome-exe-thumbnailer#9]
Gnome 3 and possibly others can make folders for all shortcuts from the same category, hence it would be useful to have all .desktop files from exe-thumbnailer  contain a 'Windows' or 'Wine' category string.

Categories=Windows;

**Comment by jlu5** [comment]
Hi,

exe-thumbnailer isn't a user facing program and doesn't ship any .desktop files. So, I'm not sure what the issue is here?
